[package]
name = "sand_commands"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "sand_commands"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
